/**
 * @file Tools.ts
 * Conceptual tools for operating on the Simulated Consciousness data.
 */
import { simulatedDB } from './Db';

/**
 * Retrieves all data generated by a specific agent.
 * @param agentName The name of the agent.
 * @returns A list of data generation records.
 */
export function getGenerationsByAgent(agentName: string) {
    return simulatedDB.queryByAgent(agentName);
}
